#!/bin/bash
# Cervantes Installer - created and maintained by vHost
# General
DEV=0
INSTALLER_VERSION="v1.2.08"
STEPS=18
# Colors
BLUE='\033[0;36m'
GREEN='\033[0;92m'
YELLOW='\033[0;93m'
NC='\033[0m'

# Credentials
USERID=$(date +%s | sha256sum | base64 | head -c 3 ; echo)
USERPASS=$(date +%s | sha256sum | base64 | head -c 6 ; echo)
RATHENAPASS="ch4ngem3"
RAGSQLPASS=$(date +%s | sha256sum | base64 | head -c 10 ; echo)

# URLs
URL_RA="https://rathena.org/board"
URL_RAGIT="https://github.com/rathena/rathena"
URL_FLUXGIT="https://github.com/rathena/FluxCP"
URL_FULLCLIENT="https://drive.google.com/uc?export=download&confirm=sM6X&id=1WnepJCHKlWaPwVnoD4DaXgO-Io07DSbT"
SERVER_IPLIST=$(ip addr|awk '/eth0/ && /inet/ {gsub(/\/[0-9][0-9]/,""); print $2}')
SERVER_IP=$(echo $SERVER_IPLIST | cut -d ' ' -f 1 )

if [ $DEV -eq 1 ]
then
	VERSION="${INSTALLER_VERSION} - ${YELLOW}Development Script${NC}"
else
	VERSION="${INSTALLER_VERSION}"
fi

echo "\033c"
echo "Welcome to ${BLUE}Cervantes${NC}, an unattended installer by vHost"
echo "Version: ${VERSION}\n"
echo "This script will now begin to install stuff on your system. Please be patient as this could take a while!\n"



















echo "${BLUE}Step 6/${STEPS}:${NC} Installing rA specific packages"
echo " * Installing git, make, g++"
apt-get -qy install git make libmariadb-dev libmariadbclient-dev libmariadbclient-dev-compat > /dev/null
echo " * Installing Utilities"
apt-get -qy install zlib1g-dev libpcre3-dev nano zip unzip zenity gcc g++ > /dev/null
echo ""



echo "${BLUE}Step 7/${STEPS}:${NC} Creating User: sagro"
echo "${YELLOW}This process is automatic and doesn't require user input.${NC}"
echo "${YELLOW}Please do not type at the password prompt.${NC}"
wget -q https://github.com/gamingmagic/unattended-installer/raw/master/createuser.zip
unzip -qq createuser.zip
chmod +x createuser.sh
./createuser.sh $RATHENAPASS
rm createuser.sh
gpasswd -a sagro sudo
echo ""



echo "${BLUE}Step 8/${STEPS}:${NC} Setting Up Desktop Stuff"
mkdir -p /usr/share/cervantes/
cd /usr/share/cervantes/
wget -q https://github.com/gamingmagic/unattended-installer/raw/master/files.zip
unzip -qq files.zip
cd links
mkdir -p /home/sagro/Desktop
cp -R * /home/sagro/Desktop
cd /usr/share/cervantes/scripts
chmod +x *
cd /home/sagro/Desktop
chmod +x *
echo ""



echo "${BLUE}Step 9/${STEPS}:${NC} Creating VNC Server Start-up Files"
cd /usr/local/bin
wget -q https://github.com/gamingmagic/unattended-installer/raw/master/myvncserver.zip
unzip -qq myvncserver.zip
chmod +x myvncserver
cd /lib/systemd/system/
wget -q https://github.com/gamingmagic/unattended-installer/raw/master/myvncserver2.zip
unzip -qq myvncserver2.zip
systemctl daemon-reload
systemctl enable myvncserver2.service
echo ""



echo "${BLUE}Step 10/${STEPS}:${NC} Installing Cervantes Files"
chown -R sagro:sagro /home/sagro
chown -R sagro:sagro /usr/share/cervantes
cd /home/sagro
sudo -u sagro sh -c "wget -q https://github.com/gamingmagic/unattended-installer/raw/master/vnc.zip"
sudo -u sagro sh -c "unzip -qq vnc.zip"
sudo -u sagro sh -c "chmod +x vnc.sh"
sudo -u sagro sh -c "./vnc.sh $RATHENAPASS"
rm vnc.sh
sudo -u sagro sh -c "myvncserver stop"
mkdir -p /home/sagro/.config/xfce4/xfconf/xfce-perchannel-xml/
touch /home/sagro/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml
echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" >> /home/sagro/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml
echo "<channel name=\"xfce4-desktop\" version=\"1.0\">" >> /home/sagro/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml
echo "  <property name=\"backdrop\" type=\"empty\">" >> /home/sagro/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml
echo "    <property name=\"screen0\" type=\"empty\">" >> /home/sagro/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml
echo "      <property name=\"monitor0\" type=\"empty\">" >> /home/sagro/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml
echo "        <property name=\"brightness\" type=\"empty\"/>" >> /home/sagro/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml
echo "        <property name=\"color1\" type=\"empty\"/>" >> /home/sagro/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml
echo "        <property name=\"color2\" type=\"empty\"/>" >> /home/sagro/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml
echo "        <property name=\"color-style\" type=\"empty\"/>" >> /home/sagro/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml
echo "        <property name=\"image-path\" type=\"string\" value=\"/usr/share/cervantes/img/bg.png\"/>" >> /home/sagro/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml
echo "        <property name=\"image-show\" type=\"empty\"/>" >> /home/sagro/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml
echo "        <property name=\"last-image\" type=\"empty\"/>" >> /home/sagro/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml
echo "        <property name=\"last-single-image\" type=\"string\" value=\"/usr/share/cervantes/img/bg.png\"/>" >> /home/sagro/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml
echo "      </property>" >> /home/sagro/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml
echo "    </property>" >> /home/sagro/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml
echo "  </property>" >> /home/sagro/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml
echo "  <property name=\"desktop-icons\" type=\"empty\">" >> /home/sagro/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml
echo "    <property name=\"icon-size\" type=\"uint\" value=\"32\"/>" >> /home/sagro/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml
echo "  </property>" >> /home/sagro/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml
echo "</channel>" >> /home/sagro/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml

touch /home/sagro/.config/mimeapps.list
echo "[Default Applications]" >> /home/sagro/.config/mimeapps.list
echo "text/plain=mousepad.desktop" >> /home/sagro/.config/mimeapps.list
echo "" >> /home/sagro/.config/mimeapps.list
echo "[Added Associations]" >> /home/sagro/.config/mimeapps.list
echo "text/plain=mousepad.desktop;" >> /home/sagro/.config/mimeapps.list
echo ""
chown -R sagro:sagro /home/sagro/



echo "${BLUE}Step 11/${STEPS}:${NC} Grabbing rA Source Files"
sudo -u sagro sh -c "git clone -q ${URL_RAGIT} /home/sagro/Desktop/rAthena/"
echo ""


















touch /home/sagro/Desktop/Info.txt
echo "Cervantes\n" >> /home/sagro/Desktop/Info.txt
echo "Server IP: ${SERVER_IP}\n" >> /home/sagro/Desktop/Info.txt
echo "-- MySQL --" >> /home/sagro/Desktop/Info.txt
echo "root password is 'ragnarok', but can only be accessed locally from this system." >> /home/sagro/Desktop/Info.txt
echo "For all other MySQL uses, please use the following credentials:" >> /home/sagro/Desktop/Info.txt
echo "User: ragnarok" >> /home/sagro/Desktop/Info.txt
echo "Password: princess21\n" >> /home/sagro/Desktop/Info.txt





echo "-- phpMyAdmin --" >> /home/sagro/Desktop/Info.txt
echo " * Access phpMyAdmin from this server using the browser and going to http://localhost/phpmyadmin" >> /home/sagro/Desktop/Info.txt
echo " or" >> /home/sagro/Desktop/Info.txt
echo " * Access phpMyAdmin from anywhere by browsing to http://${SERVER_IP}/phpmyadmin" >> /home/sagro/Desktop/Info.txt
echo "Access from root user is disabled, so you will need to login as 'ragnarok' with your MySQL password.\n" >> /home/sagro/Desktop/Info.txt

echo "-- Full Client --" >> /home/sagro/Desktop/Info.txt
echo "A full client will be made available to you on your downloads page straight" >> /home/sagro/Desktop/Info.txt
echo " after completing the FluxCP installation process. This is located at:" >> /home/sagro/Desktop/Info.txt
echo " * URL: http://${SERVER_IP}/?module=pages&action=content&page=downloads" >> /home/sagro/Desktop/Info.txt
echo " * Filesystem: FluxCP Desktop Shortcut -> downloads folder" >> /home/sagro/Desktop/Info.txt



echo "${BLUE}Step 18/${STEPS}:${NC} Finishing up!"
sudo -u sagro sh -c "myvncserver start"
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo "${YELLOW}*****************************************************************${NC}"
echo ""
echo "${BLUE}All done!${NC}"
echo "${GREEN} -- System Stuff${NC}"
echo "Linux User 'sagro' Password: ${RATHENAPASS}"
echo "Server IP: ${SERVER_IP}"
echo ""
echo "${GREEN} -- MySQL Stuff${NC}"
echo "MySQL user: ragnarok"
echo "MySQL password: princess21"
echo "phpMyAdmin: http://${SERVER_IP}/phpmyadmin"
echo ""
echo "${GREEN} -- VNC Stuff${NC}"
echo "VNC Password: ch4ngem3"
echo "We recommend TightVNC Viewer: http://www.tightvnc.com/download.php"
echo "In the Remote Host box, type ${SERVER_IP}:1"
echo ""
echo "${GREEN} -- FluxCP Stuff${NC}"
echo "Control Panel: http://${SERVER_IP}/"
echo "After FluxCP installation, full installer will be available via your site."
echo ""
echo "${BLUE}You can now login via VNC and click Start rAthena on the desktop.${NC}"
echo "${YELLOW}*****************************************************************${NC}"
rm /home/cerv
exit 0
